name: Reusable Linter

on:
  workflow_call:
    inputs:
      paths:
        required: false
        type: string
        default: '.'

      clang-format-path:
        required: false
        type: string
        default: '.clang-format'
    secrets:
      REPO_TOKEN:
        required: true
      CI_USER_APP_ID:
        required: true
      CI_USER_PRIVATE_KEY:
        required: true

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Generate token for pulling private repo
        uses: actions/create-github-app-token@v1.5.0
        id: generate_token
        with:
          app-id: ${{ secrets.CI_USER_APP_ID }}
          private-key: ${{ secrets.CI_USER_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Run C/C++ Linter
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        with:
          version: 18
          style: file
