name: Test

on:
  push

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Generate token for pulling private repos
        uses: actions/create-github-app-token@v1.5.0
        id: generate_token
        with:
          app-id: ${{ secrets.CI_USER_APP_ID }}
          private-key: ${{ secrets.CI_USER_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
